# Caletzza Theme — Shopify CLI
# Reemplaza TU-TIENDA-DEV con tu development store de Partner

[environments.default]
store = "TU-TIENDA-DEV.myshopify.com"
# theme = ""  # Vacío = crea/sube como borrador

[environments.draft]
store = "TU-TIENDA-DEV.myshopify.com"
