# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cod-express"
client_id = "YOUR_CLIENT_ID"
application_url = "https://YOUR_APP_HOST"
embedded = true

[access_scopes]
scopes = "write_draft_orders,write_orders,read_products"

[auth]
redirect_urls = [ "https://YOUR_APP_HOST/auth/callback" ]

[app_proxy]
url = "https://YOUR_APP_HOST/proxy/order"
subpath = "cod-express"
prefix = "apps"

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
